name: testmarketplaceaction
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hello world demo
        uses: tulikapgit/containeractiondemo@V1.0.0
        with:
          who-to-greet: 'demouserlocal'
